/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wynntils_antiope_manager_activity_ActivityManager */

#ifndef _Included_com_wynntils_antiope_manager_activity_ActivityManager
#define _Included_com_wynntils_antiope_manager_activity_ActivityManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wynntils_antiope_manager_activity_ActivityManager
 * Method:    registerCommand
 * Signature: (JLjava/lang/String;)Lcom/wynntils/antiope/core/type/Result;
 */
JNIEXPORT jobject JNICALL Java_com_wynntils_antiope_manager_activity_ActivityManager_registerCommand
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_wynntils_antiope_manager_activity_ActivityManager
 * Method:    registerSteam
 * Signature: (JI)Lcom/wynntils/antiope/core/type/Result;
 */
JNIEXPORT jobject JNICALL Java_com_wynntils_antiope_manager_activity_ActivityManager_registerSteam
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_wynntils_antiope_manager_activity_ActivityManager
 * Method:    updateActivity
 * Signature: (JJLjava/util/function/Consumer;)V
 */
JNIEXPORT void JNICALL Java_com_wynntils_antiope_manager_activity_ActivityManager_updateActivity
  (JNIEnv *, jobject, jlong, jlong, jobject);

/*
 * Class:     com_wynntils_antiope_manager_activity_ActivityManager
 * Method:    clearActivity
 * Signature: (JLjava/util/function/Consumer;)V
 */
JNIEXPORT void JNICALL Java_com_wynntils_antiope_manager_activity_ActivityManager_clearActivity
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     com_wynntils_antiope_manager_activity_ActivityManager
 * Method:    sendRequestReply
 * Signature: (JJILjava/util/function/Consumer;)V
 */
JNIEXPORT void JNICALL Java_com_wynntils_antiope_manager_activity_ActivityManager_sendRequestReply
  (JNIEnv *, jobject, jlong, jlong, jint, jobject);

/*
 * Class:     com_wynntils_antiope_manager_activity_ActivityManager
 * Method:    sendInvite
 * Signature: (JJILjava/lang/String;Ljava/util/function/Consumer;)V
 */
JNIEXPORT void JNICALL Java_com_wynntils_antiope_manager_activity_ActivityManager_sendInvite
  (JNIEnv *, jobject, jlong, jlong, jint, jstring, jobject);

/*
 * Class:     com_wynntils_antiope_manager_activity_ActivityManager
 * Method:    acceptRequest
 * Signature: (JJLjava/util/function/Consumer;)V
 */
JNIEXPORT void JNICALL Java_com_wynntils_antiope_manager_activity_ActivityManager_acceptRequest
  (JNIEnv *, jobject, jlong, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
