/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wynntils_antiope_manager_activity_type_Activity */

#ifndef _Included_com_wynntils_antiope_manager_activity_type_Activity
#define _Included_com_wynntils_antiope_manager_activity_type_Activity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wynntils_antiope_manager_activity_type_Activity
 * Method:    allocate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_wynntils_antiope_manager_activity_type_Activity_allocate
  (JNIEnv *, jobject);

/*
 * Class:     com_wynntils_antiope_manager_activity_type_Activity
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_wynntils_antiope_manager_activity_type_Activity_free
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_wynntils_antiope_manager_activity_type_Activity
 * Method:    getApplicationId
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_wynntils_antiope_manager_activity_type_Activity_getApplicationId
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_wynntils_antiope_manager_activity_type_Activity
 * Method:    getName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wynntils_antiope_manager_activity_type_Activity_getName
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_wynntils_antiope_manager_activity_type_Activity
 * Method:    setState
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_wynntils_antiope_manager_activity_type_Activity_setState
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_wynntils_antiope_manager_activity_type_Activity
 * Method:    getState
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wynntils_antiope_manager_activity_type_Activity_getState
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_wynntils_antiope_manager_activity_type_Activity
 * Method:    setDetails
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_wynntils_antiope_manager_activity_type_Activity_setDetails
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_wynntils_antiope_manager_activity_type_Activity
 * Method:    getDetails
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wynntils_antiope_manager_activity_type_Activity_getDetails
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_wynntils_antiope_manager_activity_type_Activity
 * Method:    setType
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_wynntils_antiope_manager_activity_type_Activity_setType
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_wynntils_antiope_manager_activity_type_Activity
 * Method:    getType
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_wynntils_antiope_manager_activity_type_Activity_getType
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_wynntils_antiope_manager_activity_type_Activity
 * Method:    getTimestamps
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_wynntils_antiope_manager_activity_type_Activity_getTimestamps
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_wynntils_antiope_manager_activity_type_Activity
 * Method:    getAssets
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_wynntils_antiope_manager_activity_type_Activity_getAssets
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_wynntils_antiope_manager_activity_type_Activity
 * Method:    getParty
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_wynntils_antiope_manager_activity_type_Activity_getParty
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_wynntils_antiope_manager_activity_type_Activity
 * Method:    getSecrets
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_wynntils_antiope_manager_activity_type_Activity_getSecrets
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_wynntils_antiope_manager_activity_type_Activity
 * Method:    setInstance
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_wynntils_antiope_manager_activity_type_Activity_setInstance
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     com_wynntils_antiope_manager_activity_type_Activity
 * Method:    getInstance
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wynntils_antiope_manager_activity_type_Activity_getInstance
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
