/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wynntils_antiope_manager_activity_type_ActivitySecrets */

#ifndef _Included_com_wynntils_antiope_manager_activity_type_ActivitySecrets
#define _Included_com_wynntils_antiope_manager_activity_type_ActivitySecrets
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wynntils_antiope_manager_activity_type_ActivitySecrets
 * Method:    setMatchSecret
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_wynntils_antiope_manager_activity_type_ActivitySecrets_setMatchSecret
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_wynntils_antiope_manager_activity_type_ActivitySecrets
 * Method:    getMatchSecret
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wynntils_antiope_manager_activity_type_ActivitySecrets_getMatchSecret
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_wynntils_antiope_manager_activity_type_ActivitySecrets
 * Method:    setJoinSecret
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_wynntils_antiope_manager_activity_type_ActivitySecrets_setJoinSecret
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_wynntils_antiope_manager_activity_type_ActivitySecrets
 * Method:    getJoinSecret
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wynntils_antiope_manager_activity_type_ActivitySecrets_getJoinSecret
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_wynntils_antiope_manager_activity_type_ActivitySecrets
 * Method:    setSpectateSecret
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_wynntils_antiope_manager_activity_type_ActivitySecrets_setSpectateSecret
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_wynntils_antiope_manager_activity_type_ActivitySecrets
 * Method:    getSpectateSecret
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wynntils_antiope_manager_activity_type_ActivitySecrets_getSpectateSecret
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
