/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wynntils_antiope_manager_activity_type_ActivityTimestamps */

#ifndef _Included_com_wynntils_antiope_manager_activity_type_ActivityTimestamps
#define _Included_com_wynntils_antiope_manager_activity_type_ActivityTimestamps
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wynntils_antiope_manager_activity_type_ActivityTimestamps
 * Method:    setStart
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_wynntils_antiope_manager_activity_type_ActivityTimestamps_setStart
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_wynntils_antiope_manager_activity_type_ActivityTimestamps
 * Method:    getStart
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_wynntils_antiope_manager_activity_type_ActivityTimestamps_getStart
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_wynntils_antiope_manager_activity_type_ActivityTimestamps
 * Method:    setEnd
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_wynntils_antiope_manager_activity_type_ActivityTimestamps_setEnd
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_wynntils_antiope_manager_activity_type_ActivityTimestamps
 * Method:    getEnd
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_wynntils_antiope_manager_activity_type_ActivityTimestamps_getEnd
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
