/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wynntils_antiope_core_type_CreateParams */

#ifndef _Included_com_wynntils_antiope_core_type_CreateParams
#define _Included_com_wynntils_antiope_core_type_CreateParams
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wynntils_antiope_core_type_CreateParams
 * Method:    allocate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_wynntils_antiope_core_type_CreateParams_allocate
  (JNIEnv *, jobject);

/*
 * Class:     com_wynntils_antiope_core_type_CreateParams
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_wynntils_antiope_core_type_CreateParams_free
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_wynntils_antiope_core_type_CreateParams
 * Method:    setClientID
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_wynntils_antiope_core_type_CreateParams_setClientID
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_wynntils_antiope_core_type_CreateParams
 * Method:    getClientID
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_wynntils_antiope_core_type_CreateParams_getClientID
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_wynntils_antiope_core_type_CreateParams
 * Method:    setFlags
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_wynntils_antiope_core_type_CreateParams_setFlags
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_wynntils_antiope_core_type_CreateParams
 * Method:    getFlags
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_wynntils_antiope_core_type_CreateParams_getFlags
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_wynntils_antiope_core_type_CreateParams
 * Method:    registerEventHandler
 * Signature: (JLcom/wynntils/antiope/event/DiscordEventAdapter;)V
 */
JNIEXPORT void JNICALL Java_com_wynntils_antiope_core_type_CreateParams_registerEventHandler
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     com_wynntils_antiope_core_type_CreateParams
 * Method:    getDefaultFlags
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_wynntils_antiope_core_type_CreateParams_getDefaultFlags
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
