/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wynntils_antiope_manager_activity_type_ActivityParty */

#ifndef _Included_com_wynntils_antiope_manager_activity_type_ActivityParty
#define _Included_com_wynntils_antiope_manager_activity_type_ActivityParty
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wynntils_antiope_manager_activity_type_ActivityParty
 * Method:    setID
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_wynntils_antiope_manager_activity_type_ActivityParty_setID
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_wynntils_antiope_manager_activity_type_ActivityParty
 * Method:    getID
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wynntils_antiope_manager_activity_type_ActivityParty_getID
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_wynntils_antiope_manager_activity_type_ActivityParty
 * Method:    getSize
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_wynntils_antiope_manager_activity_type_ActivityParty_getSize
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
