/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wynntils_antiope_manager_activity_type_ActivityAssets */

#ifndef _Included_com_wynntils_antiope_manager_activity_type_ActivityAssets
#define _Included_com_wynntils_antiope_manager_activity_type_ActivityAssets
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wynntils_antiope_manager_activity_type_ActivityAssets
 * Method:    setLargeImage
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_wynntils_antiope_manager_activity_type_ActivityAssets_setLargeImage
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_wynntils_antiope_manager_activity_type_ActivityAssets
 * Method:    getLargeImage
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wynntils_antiope_manager_activity_type_ActivityAssets_getLargeImage
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_wynntils_antiope_manager_activity_type_ActivityAssets
 * Method:    setLargeText
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_wynntils_antiope_manager_activity_type_ActivityAssets_setLargeText
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_wynntils_antiope_manager_activity_type_ActivityAssets
 * Method:    getLargeText
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wynntils_antiope_manager_activity_type_ActivityAssets_getLargeText
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_wynntils_antiope_manager_activity_type_ActivityAssets
 * Method:    setSmallImage
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_wynntils_antiope_manager_activity_type_ActivityAssets_setSmallImage
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_wynntils_antiope_manager_activity_type_ActivityAssets
 * Method:    getSmallImage
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wynntils_antiope_manager_activity_type_ActivityAssets_getSmallImage
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_wynntils_antiope_manager_activity_type_ActivityAssets
 * Method:    setSmallText
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_wynntils_antiope_manager_activity_type_ActivityAssets_setSmallText
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_wynntils_antiope_manager_activity_type_ActivityAssets
 * Method:    getSmallText
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wynntils_antiope_manager_activity_type_ActivityAssets_getSmallText
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
