/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wynntils_antiope_DiscordGameSDKCore */

#ifndef _Included_com_wynntils_antiope_DiscordGameSDKCore
#define _Included_com_wynntils_antiope_DiscordGameSDKCore
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wynntils_antiope_DiscordGameSDKCore
 * Method:    initDiscordNative
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_wynntils_antiope_DiscordGameSDKCore_initDiscordNative
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_wynntils_antiope_DiscordGameSDKCore
 * Method:    create
 * Signature: (J)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_wynntils_antiope_DiscordGameSDKCore_create
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_wynntils_antiope_DiscordGameSDKCore
 * Method:    destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_wynntils_antiope_DiscordGameSDKCore_destroy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_wynntils_antiope_DiscordGameSDKCore
 * Method:    getActivityManager
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_wynntils_antiope_DiscordGameSDKCore_getActivityManager
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_wynntils_antiope_DiscordGameSDKCore
 * Method:    getUserManager
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_wynntils_antiope_DiscordGameSDKCore_getUserManager
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_wynntils_antiope_DiscordGameSDKCore
 * Method:    getOverlayManager
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_wynntils_antiope_DiscordGameSDKCore_getOverlayManager
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_wynntils_antiope_DiscordGameSDKCore
 * Method:    getRelationshipManager
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_wynntils_antiope_DiscordGameSDKCore_getRelationshipManager
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_wynntils_antiope_DiscordGameSDKCore
 * Method:    getImageManager
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_wynntils_antiope_DiscordGameSDKCore_getImageManager
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_wynntils_antiope_DiscordGameSDKCore
 * Method:    getLobbyManager
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_wynntils_antiope_DiscordGameSDKCore_getLobbyManager
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_wynntils_antiope_DiscordGameSDKCore
 * Method:    getNetworkManager
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_wynntils_antiope_DiscordGameSDKCore_getNetworkManager
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_wynntils_antiope_DiscordGameSDKCore
 * Method:    getVoiceManager
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_wynntils_antiope_DiscordGameSDKCore_getVoiceManager
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_wynntils_antiope_DiscordGameSDKCore
 * Method:    runCallbacks
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_wynntils_antiope_DiscordGameSDKCore_runCallbacks
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_wynntils_antiope_DiscordGameSDKCore
 * Method:    setLogHook
 * Signature: (JILjava/util/function/BiConsumer;)V
 */
JNIEXPORT void JNICALL Java_com_wynntils_antiope_DiscordGameSDKCore_setLogHook
  (JNIEnv *, jobject, jlong, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
