/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wynntils_antiope_manager_activity_type_ActivityPartySize */

#ifndef _Included_com_wynntils_antiope_manager_activity_type_ActivityPartySize
#define _Included_com_wynntils_antiope_manager_activity_type_ActivityPartySize
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wynntils_antiope_manager_activity_type_ActivityPartySize
 * Method:    setCurrentSize
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_wynntils_antiope_manager_activity_type_ActivityPartySize_setCurrentSize
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_wynntils_antiope_manager_activity_type_ActivityPartySize
 * Method:    getCurrentSize
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_wynntils_antiope_manager_activity_type_ActivityPartySize_getCurrentSize
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_wynntils_antiope_manager_activity_type_ActivityPartySize
 * Method:    setMaxSize
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_wynntils_antiope_manager_activity_type_ActivityPartySize_setMaxSize
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_wynntils_antiope_manager_activity_type_ActivityPartySize
 * Method:    getMaxSize
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_wynntils_antiope_manager_activity_type_ActivityPartySize_getMaxSize
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
